### ISSUE TITLE
Cuidado con el "Firebase.js" jeje

### ISSUE THREAD

**Issue by EyderACM** [alanmoraales/login-react-firebase#1]
Hay bots en Github (como "malware") que automáticamente encuentran tus keys y utilizan tus bases de datos para sus propios servicios. Es mejor colocar ese archivo en el .gitignroe o ocultarlo para que no te roben la cuenta de Firebase jeje.

Buen proyecto para aprender React btw.

**Comment by alanmoraales** [comment]
No manches, lo borraré entonces jajajajajajajajaja. Gracias :)

**Comment by EyderACM** [comment]
De nada 👌
